apiVersion: batch/v1
kind: Job
metadata:
  name: audiblytics-seed
  namespace: audiblytics
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: seed
          imagePullPolicy: Always
