apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiblytics
resources:
  - ../../components/seed-job
images:
  - name: audiblytics-api
    newName: ghcr.io/priiyank-xd/audiblytics-api
    newTag: latest
patches:
  - path: image-patch.yaml
